script:
  - "test/travis.rb"

language: node_js
node_js:
  - 8.7.0
cache:
  directories:
    - node_modules
before_install:
  - npm install
before_script:
  - npm install node-sass -g
script:
  - npm rebuild node-sass
  - node-sass public/sass/main.scss public/css/style.css
